// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9jCeCGLtvfWg0hNWp2oD1GVGqTkNB6nY',
    appId: '1:81619253503:web:82a260cb385d024c25f4ca',
    messagingSenderId: '81619253503',
    projectId: 'stockify-f4f81',
    authDomain: 'stockify-f4f81.firebaseapp.com',
    storageBucket: 'stockify-f4f81.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIodaodWYSPOX4_KveMZ6wqWpV2uX2nSY',
    appId: '1:81619253503:android:d7dd68e6dd10443625f4ca',
    messagingSenderId: '81619253503',
    projectId: 'stockify-f4f81',
    storageBucket: 'stockify-f4f81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe48cZ3ISb9MKc4ddRgklZJELN4coRfzE',
    appId: '1:81619253503:ios:961faefc2fa48a1925f4ca',
    messagingSenderId: '81619253503',
    projectId: 'stockify-f4f81',
    storageBucket: 'stockify-f4f81.firebasestorage.app',
    iosBundleId: 'com.example.stockify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe48cZ3ISb9MKc4ddRgklZJELN4coRfzE',
    appId: '1:81619253503:ios:961faefc2fa48a1925f4ca',
    messagingSenderId: '81619253503',
    projectId: 'stockify-f4f81',
    storageBucket: 'stockify-f4f81.firebasestorage.app',
    iosBundleId: 'com.example.stockify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9jCeCGLtvfWg0hNWp2oD1GVGqTkNB6nY',
    appId: '1:81619253503:web:1ba2bb69bc148d2b25f4ca',
    messagingSenderId: '81619253503',
    projectId: 'stockify-f4f81',
    authDomain: 'stockify-f4f81.firebaseapp.com',
    storageBucket: 'stockify-f4f81.firebasestorage.app',
  );
}
